
post http://localhost:3003/api/login/
Content-Type: application/json

{
    "username":"user2",
    "password":"pass"
}
###
GET http://localhost:3003/api/blogs/
###

post http://localhost:3003/api/users/
Content-Type: application/json

{
    "username":"user3",
    "password":"pass"
}
###
post http://localhost:3003/api/login/
Content-Type: application/json

{
    "username":"nouser",
    "password":"pass"
}
###
###
GET http://localhost:3003/api/users/